/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adriano.mainMenu;

import org.jdesktop.swingx.prompt.PromptSupport;
import com.adriano.pi.DAO.DAOlogin;
import com.adriano.pi.DAO.DAOpessoas;
import com.adriano.pi.DAO.DataSource;
import com.adriano.pi.model.ModelLogin;
import com.adriano.pi.model.ModelPessoas;
import com.adriano.pi.telas.JDlogin;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author adR
 */
public class JFRhome extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();

    String caminhook = "src\\main\\resources\\verificar.png";
    ImageIcon ok = new ImageIcon(caminhook);

    String caminhoerro = "src\\main\\resources\\erro.png";
    ImageIcon erro = new ImageIcon(caminhoerro);
        MaskFormatter cpf;
        MaskFormatter data;
    /**
     * Creates new form JFRhome
     */
    public JFRhome() {
        FlatLightLaf.setup();
        initComponents();
        clearMainPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        button_inserir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        button_Consultar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        button_paginaInicial = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panel_git = new javax.swing.JPanel();
        git = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelInserir = new javax.swing.JPanel();
        JTFidade = new javax.swing.JTextField();
        JTFnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFaltura = new javax.swing.JTextField();
        button_Salvar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTFpeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFresidente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JTFcaracteristicas = new javax.swing.JTextField();
        try{data = new MaskFormatter("##/##/####");
            data.setPlaceholderCharacter('_');
            JTFdtNascimento = new javax.swing.JFormattedTextField(data);
            cpf = new MaskFormatter("###.###.###-##");
            cpf.setPlaceholderCharacter('_');
            JTFcpf = new javax.swing.JFormattedTextField(cpf);
            panelConsultar = new javax.swing.JPanel();
            jScrollPane1 = new javax.swing.JScrollPane(JTconsulta);
            JTconsulta = new javax.swing.JTable();
            JTFpesquisar = new javax.swing.JTextField();
            jButton1 = new javax.swing.JButton();
            JBExcluir = new javax.swing.JButton();
            JBlimpar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Pessoas Desaparecidas");
            setResizable(false);
            setSize(new Dimension(800, 800));

            bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            sidebar.setBackground(new java.awt.Color(54, 39, 89));

            button_inserir.setBackground(new java.awt.Color(54, 39, 89));

            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(204, 204, 204));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel1.setText(" Inserir");
            jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel1MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel1MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel1MouseExited(evt);
                }
            });

            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_insert_page_20px.png"))); // NOI18N

            javax.swing.GroupLayout button_inserirLayout = new javax.swing.GroupLayout(button_inserir);
            button_inserir.setLayout(button_inserirLayout);
            button_inserirLayout.setHorizontalGroup(
                button_inserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_inserirLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            button_inserirLayout.setVerticalGroup(
                button_inserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            button_Consultar.setBackground(new java.awt.Color(54, 39, 89));
            button_Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    button_ConsultarMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    button_ConsultarMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    button_ConsultarMouseExited(evt);
                }
            });

            jLabel13.setBackground(new java.awt.Color(54, 39, 89));
            jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(204, 204, 204));
            jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel13.setText(" Consultar");
            jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel13.setFocusable(false);
            jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel13MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel13MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel13MouseExited(evt);
                }
            });

            jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_client_20px.png"))); // NOI18N

            javax.swing.GroupLayout button_ConsultarLayout = new javax.swing.GroupLayout(button_Consultar);
            button_Consultar.setLayout(button_ConsultarLayout);
            button_ConsultarLayout.setHorizontalGroup(
                button_ConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_ConsultarLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            button_ConsultarLayout.setVerticalGroup(
                button_ConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            button_paginaInicial.setBackground(new java.awt.Color(54, 39, 89));

            jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(204, 204, 204));
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel12.setText(" Pagina Inicial");
            jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel12MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel12MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel12MouseExited(evt);
                }
            });

            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_20px.png"))); // NOI18N

            javax.swing.GroupLayout button_paginaInicialLayout = new javax.swing.GroupLayout(button_paginaInicial);
            button_paginaInicial.setLayout(button_paginaInicialLayout);
            button_paginaInicialLayout.setHorizontalGroup(
                button_paginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_paginaInicialLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            button_paginaInicialLayout.setVerticalGroup(
                button_paginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_paginaInicialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(button_paginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );

            button_paginaInicialLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel15});

            panel_git.setBackground(new java.awt.Color(54, 39, 89));

            git.setForeground(new java.awt.Color(204, 255, 204));
            git.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_github_25px_2.png"))); // NOI18N
            git.setToolTipText("Github.com");
            git.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            git.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    gitMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    gitMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    gitMouseExited(evt);
                }
            });

            javax.swing.GroupLayout panel_gitLayout = new javax.swing.GroupLayout(panel_git);
            panel_git.setLayout(panel_gitLayout);
            panel_gitLayout.setHorizontalGroup(
                panel_gitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_gitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(git)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panel_gitLayout.setVerticalGroup(
                panel_gitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_gitLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(git)
                    .addContainerGap())
            );

            jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

            jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            jLabel14.setForeground(new java.awt.Color(204, 204, 204));
            jLabel14.setText("Pessoas Desaparecidas");

            javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
            sidebar.setLayout(sidebarLayout);
            sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27))
                .addComponent(button_Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_paginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(panel_git, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidebarLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addComponent(button_paginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(button_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                    .addComponent(panel_git, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            bg.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 720));

            panelHome.setBackground(new java.awt.Color(0, 101, 163));

            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/central-de-ajuda.png"))); // NOI18N

            javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
            panelHome.setLayout(panelHomeLayout);
            panelHomeLayout.setHorizontalGroup(
                panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 824, Short.MAX_VALUE)
                    .addContainerGap())
            );
            panelHomeLayout.setVerticalGroup(
                panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(68, 68, 68))
            );

            bg.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 830, 720));

            panelInserir.setBackground(new java.awt.Color(255, 255, 255));

            JTFidade.setEditable(false);
            JTFidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            JTFnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            JTFnome.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JTFnomeActionPerformed(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel4.setText("Idade");

            jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel6.setText("Altura");

            JTFaltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            button_Salvar.setBackground(new java.awt.Color(204, 255, 204));

            jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("Salvar");
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel5MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel5MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel5MouseExited(evt);
                }
            });

            javax.swing.GroupLayout button_SalvarLayout = new javax.swing.GroupLayout(button_Salvar);
            button_Salvar.setLayout(button_SalvarLayout);
            button_SalvarLayout.setHorizontalGroup(
                button_SalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
            );
            button_SalvarLayout.setVerticalGroup(
                button_SalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            );

            jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel8.setText("Peso");

            JTFpeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel2.setText("Nome");

            jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel9.setText("Residente");

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel3.setText("CPF");

            JTFresidente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel7.setText("Data Nascimento");

            jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel10.setText("Caracteristicas");

            JTFcaracteristicas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        }catch(Exception a){

        }
        JTFdtNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTFdtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFdtNascimentoFocusLost(evt);
            }
        });

        JTFcpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTFcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInserirLayout = new javax.swing.GroupLayout(panelInserir);
        panelInserir.setLayout(panelInserirLayout);
        panelInserirLayout.setHorizontalGroup(
            panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInserirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInserirLayout.createSequentialGroup()
                        .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFnome)
                            .addComponent(JTFcaracteristicas)
                            .addGroup(panelInserirLayout.createSequentialGroup()
                                .addComponent(JTFresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                                .addComponent(button_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInserirLayout.createSequentialGroup()
                                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(panelInserirLayout.createSequentialGroup()
                        .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFdtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFidade, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInserirLayout.createSequentialGroup()
                        .addComponent(JTFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelInserirLayout.setVerticalGroup(
            panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInserirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInserirLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JTFdtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTFidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTFaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInserirLayout.createSequentialGroup()
                        .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFcaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );

        panelInserirLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JTFcpf, JTFnome});

        bg.add(panelInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 830, 710));

        panelConsultar.setBackground(new java.awt.Color(255, 255, 255));

        JTconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "DT Nascimento", "Idade", "Altura", "Peso", "Residente", "Caracteristicas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTconsulta.setColumnSelectionAllowed(true);
        JTconsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTconsulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTconsulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTconsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTconsulta);
        JTconsulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (JTconsulta.getColumnModel().getColumnCount() > 0) {
            JTconsulta.getColumnModel().getColumn(0).setMinWidth(150);
            JTconsulta.getColumnModel().getColumn(0).setMaxWidth(150);
            JTconsulta.getColumnModel().getColumn(1).setMinWidth(100);
            JTconsulta.getColumnModel().getColumn(1).setMaxWidth(100);
            JTconsulta.getColumnModel().getColumn(2).setMinWidth(120);
            JTconsulta.getColumnModel().getColumn(2).setMaxWidth(120);
            JTconsulta.getColumnModel().getColumn(3).setMinWidth(50);
            JTconsulta.getColumnModel().getColumn(3).setMaxWidth(50);
            JTconsulta.getColumnModel().getColumn(4).setMinWidth(50);
            JTconsulta.getColumnModel().getColumn(4).setMaxWidth(50);
            JTconsulta.getColumnModel().getColumn(5).setMinWidth(50);
            JTconsulta.getColumnModel().getColumn(5).setMaxWidth(50);
            JTconsulta.getColumnModel().getColumn(6).setMinWidth(70);
            JTconsulta.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBExcluir.setText("Excluir");
        JBExcluir.setEnabled(false);
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBlimpar.setText("Limpar");
        JBlimpar.setEnabled(false);
        JBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarLayout = new javax.swing.GroupLayout(panelConsultar);
        panelConsultar.setLayout(panelConsultarLayout);
        panelConsultarLayout.setHorizontalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelConsultarLayout.createSequentialGroup()
                        .addComponent(JTFpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBlimpar)))
                .addGap(20, 20, 20))
        );
        panelConsultarLayout.setVerticalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        PromptSupport.setPrompt("Pesquisar qualquer nome por letra ...", JTFpesquisar);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, JTFpesquisar);

        bg.add(panelConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 830, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearMainPanel() {
        this.button_Consultar.setEnabled(true);
        this.button_inserir.setEnabled(true);
        this.button_paginaInicial.setEnabled(true);
        JFRhome.panelInserir.setVisible(false);
        this.panelConsultar.setVisible(false);

        this.panelHome.setVisible(true);
    }


    private void JTFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFnomeActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        if (JTFnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um nome", "Erro!", HEIGHT, erro);
        } else if (JTFcpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um CPF", "Erro!", HEIGHT, erro);
        } else if (JTFdtNascimento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe uma data", "Erro!", HEIGHT, erro);
        } else if (JTFidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe uma idade", "Erro!", HEIGHT, erro);
        } else if (JTFaltura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe uma altura", "Erro!", HEIGHT, erro);
        } else if (JTFpeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um peso", "Erro!", HEIGHT, erro);
        } else if (JTFresidente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe uma cidade", "Erro!", HEIGHT, erro);
        } else {
            // cria um datasource para conexão com o banco
            DataSource dataSource = new DataSource();
            DAOpessoas pessoa = new DAOpessoas(dataSource);

            // instancia um objeto
            ModelPessoas f = new ModelPessoas();

            // pega os dados do formulário
            f.setNome(JTFnome.getText());
            f.setCpf((JTFcpf.getText()));
            f.setDataNascimento(JTFdtNascimento.getText());
            f.setIdade((JTFidade.getText()));
            f.setAtura((JTFaltura.getText()));
            f.setPeso((JTFpeso.getText()));
            f.setResidente(JTFresidente.getText());
            f.setCaracteristicas(JTFcaracteristicas.getText());

            // executa a inserção que está no MunicipioDAO
            pessoa.inserir(f);

            limpa();

        }


    }//GEN-LAST:event_jLabel5MouseClicked

    private void limpa() {
        JTFnome.setText("");
        JTFcpf.setText("");
        JTFdtNascimento.setText("");
        JTFidade.setText("");
        JTFaltura.setText("");
        JTFpeso.setText("");
        JTFresidente.setText("");
        JTFcaracteristicas.setText("");

    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panelConsultar.setVisible(false);
        panelHome.setVisible(false);
        panelInserir.setVisible(false);
        JDlogin a = new JDlogin(this, true);
        a.setVisible(true);

cpf.setPlaceholderCharacter('_');
    }//GEN-LAST:event_jLabel1MouseClicked

    private void button_ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ConsultarMouseClicked


    }//GEN-LAST:event_button_ConsultarMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        this.button_inserir.setBackground(new java.awt.Color(77, 77, 255));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        this.button_inserir.setBackground(new java.awt.Color(54, 39, 89)); //[54,39,89]
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        panelInserir.setVisible(false);
        panelHome.setVisible(false);
        panelConsultar.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void button_ConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ConsultarMouseEntered

    }//GEN-LAST:event_button_ConsultarMouseEntered

    private void button_ConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ConsultarMouseExited

    }//GEN-LAST:event_button_ConsultarMouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        this.button_Consultar.setBackground(new java.awt.Color(77, 77, 255)); //77, 77, 255
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        this.button_Consultar.setBackground(new java.awt.Color(54, 39, 89)); //[54,39,89]
    }//GEN-LAST:event_jLabel13MouseExited


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DataSource dataSource = new DataSource();
        DAOpessoas cidadeDao = new DAOpessoas(dataSource);

        ArrayList<ModelPessoas> registros = cidadeDao.ConsultaUm(JTFpesquisar.getText());

        if (registros != null && !registros.isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) JTconsulta.getModel();
            JBlimpar.setEnabled(true);
            JBExcluir.setEnabled(true);

            // limpa a consulta anterior
            modelo.setNumRows(0);

            for (ModelPessoas m : registros) {
                modelo.addRow(new Object[]{
                    m.getNome(),
                    m.getCpf(),
                    m.getDataNascimento(),
                    m.getIdade(),
                    m.getAtura(),
                    m.getPeso(),
                    m.getResidente(),
                    m.getCaracteristicas(),});
            }
            JTconsulta.setModel(modelo);

            // cria variável para o JTable
            JTconsulta.getColumnModel().getColumn(0).setPreferredWidth(20);
  

//            JTconsulta.getColumnModel().getColumn(1).setPreferredWidth(10);
//            JTconsulta.getColumnModel().getColumn(2).setPreferredWidth(10);
//            JTconsulta.getColumnModel().getColumn(3).setPreferredWidth(5);
//            JTconsulta.getColumnModel().getColumn(4).setPreferredWidth(5);
//            JTconsulta.getColumnModel().getColumn(5).setPreferredWidth(5);
//            JTconsulta.getColumnModel().getColumn(6).setPreferredWidth(5);
//            JTconsulta.getColumnModel().getColumn(7).setPreferredWidth(20);

            // fecha DataSource
            dataSource.closeDataSource();

        } else {
            JOptionPane.showMessageDialog(this, "Sem resultados", "Erro!", HEIGHT, erro);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        panelConsultar.setVisible(false);
        panelInserir.setVisible(false);
        panelHome.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        this.button_paginaInicial.setBackground(new java.awt.Color(77, 77, 255));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        this.button_paginaInicial.setBackground(new java.awt.Color(54, 39, 89)); //[54,39,89]
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        this.button_Salvar.setBackground(new java.awt.Color(46, 184, 46));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        this.button_Salvar.setBackground(new java.awt.Color(204, 255, 204));
    }//GEN-LAST:event_jLabel5MouseExited

    public boolean verificaSenha(String senha) {

        DataSource dataSource = new DataSource();
        DAOlogin loginsDao = new DAOlogin(dataSource);

        for (ModelLogin a : loginsDao.Consulta()) {
            if (a.getSenha().equals(senha)) {
                return true;

            }
        }
        return false;
    }


    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed

        String senha1 = JOptionPane.showInputDialog("Insira a senha");

        if (!verificaSenha(senha1)) {
            JOptionPane.showMessageDialog(this, "Senha Errada", "Erro!", HEIGHT, erro);

        } else {
            DataSource dataSource = new DataSource();

            DAOpessoas cidadeDao = new DAOpessoas(dataSource);

            //pega o nome pela coluna 1
            String nome = JTconsulta.getValueAt(JTconsulta.getSelectedRow(), 0).toString();

            //excluir linha da tabela
            ((DefaultTableModel) JTconsulta.getModel()).removeRow(JTconsulta.getSelectedRow());

            model.setNumRows(0);
            JOptionPane.showMessageDialog(this, "Excluido com sucesso!", "OK!", HEIGHT, ok);
            cidadeDao.removerPeloNome(nome);

        }


    }//GEN-LAST:event_JBExcluirActionPerformed

    private void JBlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlimparActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) JTconsulta.getModel();

        modelo.setNumRows(0);

        JTconsulta.setModel(modelo);
    }//GEN-LAST:event_JBlimparActionPerformed

    private void gitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitMouseClicked
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI uri = new URI("https://github.com/Adriano2607");
            desktop.browse(uri);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Navegador não Encontrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(this, "URL invalida ", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_gitMouseClicked

    private void gitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitMouseEntered
        this.panel_git.setBackground(new java.awt.Color(77, 77, 255)); //77, 77, 255
    }//GEN-LAST:event_gitMouseEntered

    private void gitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitMouseExited
        this.panel_git.setBackground(new java.awt.Color(54, 39, 89)); //[54,39,89]
    }//GEN-LAST:event_gitMouseExited

    private void JTFcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcpfActionPerformed

    private void JTFdtNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFdtNascimentoFocusLost
        String a = JTFdtNascimento.getText().substring(6,10);
        System.out.println(a);
        int b  = 2023 - Integer.parseInt( a);
        System.out.println(b);
        JTFidade.setText(String.valueOf(b));
        
    }//GEN-LAST:event_JTFdtNascimentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBlimpar;
    private javax.swing.JTextField JTFaltura;
    private javax.swing.JTextField JTFcaracteristicas;
    private javax.swing.JFormattedTextField JTFcpf;
    private javax.swing.JFormattedTextField JTFdtNascimento;
    private javax.swing.JTextField JTFidade;
    private javax.swing.JTextField JTFnome;
    private javax.swing.JTextField JTFpeso;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JTextField JTFresidente;
    private javax.swing.JTable JTconsulta;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel button_Consultar;
    private javax.swing.JPanel button_Salvar;
    private javax.swing.JPanel button_inserir;
    private javax.swing.JPanel button_paginaInicial;
    private javax.swing.JLabel git;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelConsultar;
    private javax.swing.JPanel panelHome;
    public static javax.swing.JPanel panelInserir;
    private javax.swing.JPanel panel_git;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
